### PR TITLE
ci: add lumberjack-ivy CI workflow

### PR DESCRIPTION
**Pull request by LayZeeDK**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Lumberjack is a View Engine-compiled package.

Issue Number: N/A

## What is the new behavior?
A separate Lumberjack bundle with partial Ivy compilation is created. This enables faster compilation time for end-users but requires Angular CLI >=11.1. Technically it's fully Ivy-compiled because Lumberjack doesn't contain components.

This package could be published in parallel to `@ngworker/lumberjack` using a name such as `@ngworker/lumberjack-ivy` or `@ngworker/lumberjack-angular-linker`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by LayZeeDK** [comment]
Waiting for https://github.com/ngworker/angular-versions-action/pull/22.

**Comment by NachoVazquez** [comment]
This is very exciting.

**Comment by NachoVazquez** [comment]
That version should not be failing. Is that a regression?

**Comment by LayZeeDK** [comment]
> That version should not be failing. Is that a regression?

I updated the dependencies and removed `@angular-devkit/build-ng-packagr`. We then get errors because of https://github.com/ngworker/angular-versions-action/pull/22.

**Comment by LayZeeDK** [comment]
We might want to look into the schematics e2e setup to make sure it's reusing the package build artifact and not re-building the schematics sub-package for different versions of Angular.

**Pull request closed without merging**
