### PR TITLE
feat(chore): set module compiler option to es2020

### PR DESCRIPTION
**Pull request by sumitparakh**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Couldn't find any issue related to this, hence pasting backlog card here. Should I create a new issue first and then link it here?
Issue Number: https://github.com/ngworker/lumberjack/projects/1#card-50958521

## What is the new behavior?
As per the migration update guide from [angular](https://angular.io/guide/migration-update-module-and-target-compiler-options):

### Why "es2020" instead of "esnext"?
In TypeScript 3.9, the behavior of the TypeScript compiler controlled by module is the same with both "esnext" and "es2020" values. This behavior can change in the future, because the "esnext" option could evolve in a backwards incompatible ways, resulting in build-time or run-time errors during a TypeScript update. As a result, code can become unstable. Using the "es2020" option mitigates this risk.
https://angular.io/guide/migration-update-module-and-target-compiler-options#why-es2020-instead-of-esnext

### Why is this migration necessary?
This migration provides improvements to the long-term supportability of projects by updating the projects to use recommended best practice compilation options.
https://angular.io/guide/migration-update-module-and-target-compiler-options#why-is-this-migration-necessary

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NachoVazquez** [comment]
Hi @sumitparakh ! Thanks for your contribution! 

Could you please complete the PR template?

We need a bit more info about why you are suggesting these changes and what implication they could have on other's work.

Thanks again for your time.

**Comment by LayZeeDK** [comment]
FYI, this issue is related to https://github.com/ngworker/lumberjack/projects/1#card-50958521

**Comment by sumitparakh** [comment]
Hi @NachoVazquez , I updated the PR description.

**Review by LayZeeDK — CHANGES_REQUESTED** [review]
We should probably not change this value for non-publishable libraries. Using Angular versions action, they will be running older versions of Angular and TypeScript in CI workflow runs. Older versions of TypeScript do not support `"es2020"`.

To mitigate: Revert the changes made to the `test-util` projects.

**Comment by sumitparakh** [comment]
Hi @LayZeeDK , reverted `test-util` change and updated the commit message with appropriate details about the same. I am not sure why [sonar check](https://github.com/ngworker/lumberjack/pull/96/checks?check_run_id=3389666516) is failing though.

**Comment by NachoVazquez** [comment]
> Hi @LayZeeDK , reverted `test-util` change and updated the commit message with appropriate details about the same. I am not sure why [sonar check](https://github.com/ngworker/lumberjack/pull/96/checks?check_run_id=3389666516) is failing though.

That's ok @sumitparakh; it is a Github known issue. We can not use the secret key for the Sonar step when the PR is from a fork.

**Comment by NachoVazquez** [comment]
@sumitparakh I'm still seeing the changes to the `test-util` project. Are you sure you pushed correctly?

**Comment by sumitparakh** [comment]
> @sumitparakh I'm still seeing the changes to the `test-util` project. Are you sure you pushed correctly?

@NachoVazquez 

There are two `test-util`, one under `internal` and another one under `internal/console-driver`. I removed only parent internal/test-util project. Should I remove them both?

**Comment by NachoVazquez** [comment]
@all-contributors please add @sumitparakh for code

**Review by NachoVazquez — APPROVED** [review]

**Pull request merged**
