### PR TITLE
feat: add console logger

### PR DESCRIPTION
**Pull request by LayZeeDK**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
1. The Console API is used directly by the `ConsoleDriver`.

Issue Number: N/A

## What is the new behavior?
1. A `LumberjackConsole` interface has been added which is used by the `ConsoleDriver`.
1. An internal test utility for the console driver has been added with no-op and spy consoles.
1. Remove `time` barrel to prevent circular dependencies in library bundle. We should also remove other barrels.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information
Folder structure and configuration of other libraries were touched to keep things conventional.

### CODE REVIEW

**Comment by LayZeeDK** [comment]
Yes, I tried to convert it to a draft PR. It's because path mappings for the internal libraries are removed during CI for the app and e2e jobs. I'll fix it.

**Comment by LayZeeDK** [comment]
Ready for review.

**Comment by NachoVazquez** [comment]
This PR LGTM.

My only concern is that we are using the `Logger` name for different things, which could lead to confusion.

We could try something like `ConsoleTransport` or `ConsoleConduit,` but that could lead to some confusion with drivers too.

Maybe `ConsoleWrapper` is more accurate.

**Comment by LayZeeDK** [comment]
`LumberjackConsole`?

**Comment by NachoVazquez** [comment]
> `LumberjackConsole`?

That works

**Comment by LayZeeDK** [comment]
Ready for another round.

**Review by NachoVazquez — APPROVED** [review]

**Pull request merged**
